name: Build AsusWRT

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

env:
  REPO_URL: https://github.com/mrkenz9595/AsusWRT-MT7621.git
  REPO_BRANCH: master
  DEVICE_NAME: rt-mir3g
  TZ: Asia/Ho_Chi_Minh

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: mrkenz9595/AsusWRT-MT7621
        ref: ${{ env.REPO_BRANCH }}

    - name: Initialize environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"
        sudo -E apt-get update
        sudo -E apt-get -y install git autoconf automake bash bison bzip2 diffutils file flex m4 g++ gawk groff-base libncurses-dev libtool libslang2 make patch perl pkg-config shtool subversion tar texinfo zlib1g zlib1g-dev git-core gettext libexpat1-dev libssl-dev cvs gperf unzip python3 python-is-python3 libxml-parser-perl gcc-multilib libxml2-dev g++-11 g++-multilib libncurses5 mtd-utils libncurses5-dev libvorbis-dev autopoint autogen sed build-essential intltool libglib2.0-dev xutils-dev lib32z1-dev lib32stdc++6
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Prepare toolchain
      run: |
        cd AsusWRT-MT7621
        cp -r tools/brcm /opt/
        cp tools/buildroot-gcc342.tar.bz2 /opt/
        cp tools/buildroot-gcc463_32bits.tar.bz2 /opt/
        cd /opt
        tar -xf buildroot-gcc342.tar.bz2
        tar -xf buildroot-gcc463_32bits.tar.bz2
    - name: Compile firmware
      id: compile
      run: |
        export PATH=$PATH:/opt/brcm/hndtools-mipsel-linux/bin:/opt/brcm/hndtools-mipsel-uclibc/bin:/opt/buildroot-gcc463/bin
        cd AsusWRT-MT7621/release/src-ra-5010
        make -i $DEVICE_NAME
        echo "::set-output name=status::success"
        echo "DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
    - name: Upload firmware
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success'
      with:
        name: ${{ env.DEVICE_NAME }}_asuswrt_${{ env.DATE }}
        path: AsusWRT-MT7621/release/src-ra-5010/image/*.trx
